matrix:
- name: Newspeak
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .config/dictionaries/.wordlist.txt
    encoding: utf-8
    output: .wordlist.dic
  pipeline:
  - pyspelling.filters.text
  sources:
  - '*.md'
  default_encoding: utf-8